name: Deploy MkDocs Site
on:
  push:
    branches: [ "main" ]  # 建议在源分支触发
  pull_request:
    branches: [ "main" ]
permissions:
  contents: write  # 允许写入gh-pages分支[3,5](@ref)
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. 检出代码
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 获取完整提交历史[5](@ref)
      
      # 2. 设置Python
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.x"  # 使用x保持兼容性[5](@ref)
      
      # 3. 安装依赖
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocs-material
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      
      # 4. 代码检查
      - name: Lint with flake8
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      
      # 5. 构建并部署
      - name: Deploy to GitHub Pages
        run: mkdocs gh-deploy --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # 自动身份验证[3,5](@ref)
